import  FormData  from '../../components/DataModels/FormData';
import  companyLogo  from '../../components/images/defaultCompanyLogo.jpg';
import  image1  from '../../components/images/images.jpg';
const JobsData:FormData[]=[
  {
    title:'Software Developer-Fresher',
    qualification:'Btech',
    experience:'Fresher +1',
    companyName:'INFOSYS',
    companyType:'Offline',
    companyLogo:image1,
    city:'Hyderabad',
    state:'Telangana',
    country:'India',
    region:'Asia',
    postingDate:new Date('02-21-2023'),
    expiryDate:new Date('12-13-2024'),
    appClosingDate:new Date('01-03-2023'),
    removingJobDate:new Date('08-02-2023'),
    salary:15000,
    hours:8,
    jobType:'Parmanent',
    qualifications:[
      {id:'1',value:'Bachelor of Technology '},
      {id:'2',value:'Aws Cloud Computing service'},
      {id:'3',value:'Git and Github'},
    ],
    duties:[
      {id:'1',value:'Developing and maintaining all server-side network components.'},
      {id:'2',value:'Developing and maintaining all client-side UI components and interfaces.'},
      {id:'3',value:'Designing customer-facing UI and back-end services for various business processes'},
      {id:'4',value:'Developing high-performance applications by writing testable, reusable, and efficient code.'},
    ],
  },
  {
    title:'Frontend Developer-Fresher',
    qualification:'Btech',
    experience:'Seniority +2',
    companyName:'THOUGHTWORKS',
    companyType:'Online',
    companyLogo:companyLogo,
    city:'Mumbai',
    state:'Mharastra',
    country:'India',
    region:'Asia',
    postingDate:new Date('02-02-2023'),
    expiryDate:new Date('03-23-2024'),
    appClosingDate:new Date('11-10-2023'),
    removingJobDate:new Date('12-06-2023'),
    salary:1200000,
    hours:7,
    jobType:'regular',
    qualifications:[
      {id:'1',value:'Computer Science Graduate'},
      {id:'2',value:'Well familiar with Node.js '},
    ],
    duties:[
      {id:'1',value:'Implementing effective security protocols, data protection measures, and storage solutions.'},
      {id:'2',value:'Running diagnostic tests, repairing defects, and providing technical support.'},
      {id:'3',value:'Recommending and implementing improvements to processes and technologies.'},
    ],
  },
  {
    title:'Backend Developer-Fresher',
    qualification:'Btech',
    experience:'Fresher +3',
    companyName:'DELOITTE',
    companyType:'Online',
    companyLogo:companyLogo,
    city:'Delhi',
    state:'Delhi',
    country:'India',
    region:'Asia',
    postingDate:new Date('02-02-2023'),
    expiryDate:new Date('03-13-2024'),
    appClosingDate:new Date('11-10-2023'),
    removingJobDate:new Date('12-06-2023'),
    salary:50000,
    hours:8,
    jobType:'Regular',
    qualifications:[
      {id:'1',value: 'Any Degree',},
      {id:'2',value: 'Information Technology Expert'},
      {id:'3',value: 'React native of new version'},
    ],
    duties:[
      {id:'1',value:'Keeping informed of advancements in the fields of Node.js and React.js development.Keeping informed of advancements in the fields of Node.js and React.js development.'},
      {id:'2',value:'Designing DB tables and Querying Databases to validate application behaviour and perform unit tests'},
    ]
  },
];
export default JobsData;
